######################################################################
# Automatically generated by qmake (2.01a) mar. mars 13 12:32:00 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += saveItems.cpp
